[containers]
label = false

[engine]
# don't use podman compose, use docker-compose directly with DOCKER_HOST set to the
# podman socket. docker-compose directly will use the buildx builder which is better.
compose_providers = []
