input_delay 1
# 1s / 144 = 6.9ms
repaint_delay 6
sync_to_monitor yes
wayland_enable_ime no

# font_family family="Monaspace Neon" features="-calt -liga"
font_family family="Input Mono Narrow"
text_composition_strategy 1.2 30
box_drawing_scale 0.5, 1, 1.5, 2.0

allow_remote_control password
cursor_blink_interval 0
cursor_shape underline
enable_audio_bell no
enabled_layouts tall:mirrored=false;bias=55
initial_window_height 50c
initial_window_width 106c
remember_window_size no
resize_in_steps yes
scrollback_pager_history_size 100
shell_integration no-title
window_padding_width 2 6
update_check_interval 0
macos_option_as_alt yes

map f11 toggle_fullscreen
map ctrl+x>t new_tab_with_cwd
map ctrl+x>w close_tab
map ctrl+x>[ previous_tab
map ctrl+x>] next_tab
map ctrl+x>% new_window_with_cwd
map ctrl+x>o next_window
map ctrl+x>h show_last_command_output
map ctrl+x>shift+h show_scrollback
map ctrl+x>r load_config_file
map ctrl+x>q debug_config
map ctrl+x>d detach_tab ask

include theme.conf
cursor none

include ${KITTY_OS}.conf
